namespace ContactsService.Models
{
    using System;
    using MongoDB.Bson;

    public class Contact
    {
        /// <summary>
        /// The unique id generated by backend.
        /// </summary>
        public ObjectId Id { get; set; }

        /// <summary>
        /// The unique contact id.
        /// </summary>
        public Guid ContactId { get; set; }

        /// <summary>
        /// Personal information of the contact.
        /// </summary>
        public PersonalDetails PersonalInformation { get; set; }

        /// <summary>
        /// Satsang related information of the contact.
        /// </summary>
        public SatsangDetails SatsangInformation { get; set; }

        /// <summary>
        /// Work related information of the contact.
        /// </summary>
        public WorkDetails WorkInformation { get; set; }
    }
}
